# Generated by Django 5.2.7 on 2025-11-02 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the AI model, e.g., GPT-4 or Claude 3.', max_length=255)),
                ('version', models.CharField(help_text='Version or build identifier of the model.', max_length=50)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('huggingface', 'Hugging Face'), ('anthropic', 'Anthropic'), ('google', 'Google DeepMind'), ('mistral', 'Mistral AI'), ('meta', 'Meta AI'), ('custom', 'Custom / Self-Hosted')], help_text='Model provider or vendor.', max_length=50)),
                ('model_id', models.CharField(help_text="Unique identifier for the model within the provider's ecosystem.", max_length=255, unique=True)),
                ('api_key', models.CharField(blank=True, help_text='API key for accessing this model from the provider.', max_length=255, null=True)),
                ('base_url', models.URLField(blank=True, help_text='endpoint URL (for self-hosted or experimental models).', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the model’s purpose or usage context.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the model is currently available for use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='ai_model.aimodelinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI Model')], max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_model.chatsession')),
            ],
        ),
    ]
