# Generated by Django 5.2.7 on 2025-11-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0002_alter_chatsession_model_alter_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
