# Generated by Django 5.2.7 on 2025-11-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0003_chatmessage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aimodelinfo',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('leonardo', 'Leonardo AI'), ('huggingface', 'Hugging Face'), ('anthropic', 'Anthropic'), ('google', 'Google DeepMind'), ('mistral', 'Mistral AI'), ('meta', 'Meta AI'), ('custom', 'Custom / Self-Hosted')], help_text='Model provider or vendor.', max_length=50),
        ),
    ]
