# Generated by Django 5.2.7 on 2025-11-08 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0004_chatsession_summary_alter_aimodelinfo_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='ai_model.aimodelinfo'),
        ),
    ]
