# Generated by Django 5.2.7 on 2025-11-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0005_alter_chatsession_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelinfo',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('leonardo', 'Leonardo AI'), ('wavespeedai', 'Wavespeed AI'), ('google', 'Google')], help_text='Model provider or vendor.', max_length=50),
        ),
    ]
