# Generated by Django 5.2.7 on 2025-11-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0006_alter_aimodelinfo_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelinfo',
            name='base_cost',
            field=models.IntegerField(default=0, help_text='base cost in terms of words or credits for using this model'),
        ),
        migrations.AddField(
            model_name='aimodelinfo',
            name='images_generating_models',
            field=models.BooleanField(default=False, help_text='Indicates if the model supports image generation'),
        ),
    ]
