# Generated by Django 5.2.7 on 2025-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0007_aimodelinfo_base_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodelinfo',
            name='images_generating_models',
        ),
        migrations.AddField(
            model_name='aimodelinfo',
            name='model_type',
            field=models.CharField(choices=[('chat', 'chat'), ('image_editor', 'image_editor'), ('text_to_image', 'text_to_image'), ('image_to_video', 'image_to_video')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aimodelinfo',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('leonardo', 'Leonardo AI'), ('wavespeedai', 'Wavespeed AI'), ('google', 'Google'), ('falai', 'FAL AI')], help_text='Model provider or vendor.', max_length=50),
        ),
    ]
