# Generated by Django 5.2.7 on 2025-12-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0007_aimodelinfo_base_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelinfo',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('leonardo', 'Leonardo AI'), ('wavespeedai', 'Wavespeed AI'), ('google', 'Google'), ('falai', 'FAL AI')], help_text='Model provider or vendor.', max_length=50),
        ),
    ]
