# Generated by Django 5.2.7 on 2025-12-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0008_alter_aimodelinfo_provider'),
        ('ai_model', '0008_remove_aimodelinfo_images_generating_models_and_more'),
    ]

    operations = [
    ]
