# Generated by Django 5.2.7 on 2025-12-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0012_alter_aimodelinfo_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/'),
        ),
        migrations.AddField(
            model_name='aimodelinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo/'),
        ),
        migrations.AlterField(
            model_name='aimodelinfo',
            name='model_type',
            field=models.CharField(choices=[('chat', 'chat'), ('image_editor', 'image_editor'), ('text_to_image', 'text_to_image'), ('image_to_video', 'image_to_video'), ('text_to_video', 'text_to_video'), ('image_tool', 'image_tool'), ('video_upscaler', 'video_upscaler')], max_length=20, null=True),
        ),
    ]
