# Generated by Django 5.2.7 on 2025-12-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0013_aimodelinfo_image_aimodelinfo_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(choices=[('chat', 'chat'), ('image_editor', 'image_editor'), ('text_to_image', 'text_to_image'), ('image_to_video', 'image_to_video'), ('text_to_video', 'text_to_video'), ('image_tool', 'image_tool'), ('video_upscaler', 'video_upscaler')], max_length=20, null=True),
        ),
    ]
