# Generated by Django 5.2.7 on 2026-01-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0014_alter_chatsession_options_chatsession_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelinfo',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='base cost in terms of words or credits for using this model', max_digits=100),
        ),
        migrations.AlterField(
            model_name='aimodelinfo',
            name='model_type',
            field=models.CharField(choices=[('chat', 'chat'), ('image_editor', 'image_editor'), ('text_to_image', 'text_to_image'), ('image_to_video', 'image_to_video'), ('text_to_video', 'text_to_video'), ('image_tool', 'image_tool'), ('video_upscaler', 'video_upscaler'), ('image_to_3d', 'image_to_3d'), ('video_effect', 'video_effect')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aimodelinfo',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('leonardo', 'Leonardo AI'), ('wavespeedai', 'Wavespeed AI'), ('google', 'Google'), ('deepseek', 'deepseek')], help_text='Model provider or vendor.', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(choices=[('chat', 'chat'), ('image_editor', 'image_editor'), ('text_to_image', 'text_to_image'), ('image_to_video', 'image_to_video'), ('text_to_video', 'text_to_video'), ('image_tool', 'image_tool'), ('video_upscaler', 'video_upscaler'), ('image_to_3d', 'image_to_3d'), ('video_effect', 'video_effect')], max_length=20, null=True),
        ),
    ]
