# Generated by Django 5.2.7 on 2026-01-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0015_alter_aimodelinfo_base_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelinfo',
            name='model_type',
            field=models.CharField(choices=[('chat', 'chat'), ('image_editor', 'image_editor'), ('text_to_image', 'text_to_image'), ('image_to_video', 'image_to_video'), ('text_to_video', 'text_to_video'), ('text_or_image_to_video', 'text_or_image_to_video'), ('image_tool', 'image_tool'), ('video_upscaler', 'video_upscaler'), ('image_to_3d', 'image_to_3d'), ('video_effect', 'video_effect'), ('text_to_speech', 'text_to_speech')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aimodelinfo',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('wavespeedai', 'Wavespeed AI'), ('google', 'Google'), ('deepseek', 'deepseek')], help_text='Model provider or vendor.', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(choices=[('chat', 'chat'), ('image_editor', 'image_editor'), ('text_to_image', 'text_to_image'), ('image_to_video', 'image_to_video'), ('text_to_video', 'text_to_video'), ('image_tool', 'image_tool'), ('text_or_image_to_video', 'text_or_image_to_video'), ('video_upscaler', 'video_upscaler'), ('image_to_3d', 'image_to_3d'), ('video_effect', 'video_effect'), ('text_to_speech', 'text_to_speech')], max_length=50, null=True),
        ),
    ]
