# Generated by Django 5.2.7 on 2026-01-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0016_alter_aimodelinfo_model_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelinfo',
            name='base_cost',
            field=models.DecimalField(decimal_places=50, default=0, help_text='base cost in terms of words or credits for using this model', max_digits=100),
        ),
    ]
