# Generated by Django 5.2.7 on 2026-01-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0017_alter_aimodelinfo_base_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='media/voice_chat/'),
        ),
    ]
