# Generated by Django 5.2.7 on 2025-11-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoicemodel_plan_invoicemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
