# Generated by Django 5.2.7 on 2026-01-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoicemodel_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='words',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
