# Generated by Django 5.2.7 on 2025-11-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_creditaccount_credittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('add', 'Add'), ('deduct', 'Deduct'), ('refund', 'Refund'), ('bonus', 'Bonus')], max_length=10),
        ),
    ]
