# Generated by Django 5.2.7 on 2025-11-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_credittransaction_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_token_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
