# Generated by Django 5.2.7 on 2025-11-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_total_token_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittransaction',
            name='message',
        ),
    ]
