# Generated by Django 5.2.7 on 2025-11-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_credittransaction_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
