# Generated by Django 5.2.7 on 2025-11-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
