# Generated by Django 5.2.7 on 2025-12-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='word_limit',
            field=models.IntegerField(default=400),
        ),
    ]
