# Generated by Django 5.2.7 on 2025-12-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_api_limit_customuser_word_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_token_used',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
