# Generated by Django 5.2.7 on 2026-01-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_total_token_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditaccount',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
