# Generated by Django 5.2.7 on 2026-01-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_creditaccount_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_token_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000000000, null=True),
        ),
    ]
