# Generated by Django 5.2.7 on 2025-11-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('stripe_product_price_id', models.CharField(blank=True, null=True)),
                ('plan_code', models.CharField(unique=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('words_or_credits', models.IntegerField(help_text='how much word will be added in user credits ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
