# Generated by Django 5.2.7 on 2025-11-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
