# Generated by Django 5.2.7 on 2025-11-12 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_subscriptionmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('expired', 'expired')], default='active', null=True),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='subscription_duration',
            field=models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('one-time', 'one-time')], null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_subscription', to='plan.planmodel'),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
