# Generated by Django 5.2.7 on 2025-12-30 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_subscriptionmodel_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmodel',
            name='stripe_product_price_id',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='subscription_duration',
        ),
        migrations.DeleteModel(
            name='SubscriptionModel',
        ),
    ]
